application: sandinmybox
version: 1
runtime: python27
api_version: 1
threadsafe: true

# https://developers.google.com/appengine/docs/python/config/appconfig#Static_File_Handlers

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /(.*\.(htm|html|js))
  static_files: static/\1
  upload: static/(.*\.(htm|html|js))

- url: /(.*\.(jpg|png))
  static_files: static/\1
  upload: static/(.*\.(jpg|png))

- url: /py/.*
  script: main.app

- url: /admin
  script: main.app
  login: admin
